### ISSUE TITLE
Syso Container

### ISSUE THREAD

**Issue by svantja** [htwg-syslab-syso/syso-template#16]
Man kann leider keine Verbindung mehr zu den Containern herstellen, weder über die Konsole per ssh noch über X2Go (Bsys Container sind auch betroffen).
Herr Isele weiß bereits bescheid und versucht das Problem zu beheben.
Das Problem besteht seit etwa 14Uhr heute.

@steveeJ @SWW13 @mmaechtel

**Comment by SWW13** [comment]
`ct-staff-0.syslab.in.htwg-konstanz.de` is still down:

```
$ host ct-staff-0.syslab.in.htwg-konstanz.de
ct-staff-0.syslab.in.htwg-konstanz.de has address 141.37.160.31

$ ping ct-staff-0.syslab.in.htwg-konstanz.de
PING ct-staff-0.syslab.in.htwg-konstanz.de (141.37.160.31): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
```

**Comment by SWW13** [comment]
Fixed.
