### ISSUE TITLE
ci/artifacts/hw3.txt

### ISSUE THREAD

**Issue by svantja** [htwg-syslab-syso/syso-template#8]
@steveeJ @SWW13 
Is it intended that no `hw3.txt` exists in `ci/artifacts/`? 
`./ci/run-all.sh` will fail if this file is non existent.

**Comment by steveeJ** [comment]
> Is it intended that no hw3.txt exists in ci/artifacts/?

This is not intended and it seems to have been forgotten. Thanks for the report!

**Comment by SWW13** [comment]
I didn't create one because the sysHW3+ shells were not ready then.
I'll address this soon.
